name: gatekeeper
description: Gatekeeper is a Dart package for managing TCP ports with a manager, server, and client. Control ports programmatically, via IPC, or remotely for efficient port management.
version: 1.0.4
repository: https://github.com/gmpassos/gatekeeper

environment:
  sdk: ^3.6.0

executables:
  gatekeeper:
  gatekeeper_client:

dependencies:
  args_simple: ^1.1.0
  collection: ^1.19.1
  crypto: ^3.0.6
  encrypt: ^5.0.3
  pointycastle: ^3.9.1
  #base_codecs: ^1.0.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
  dependency_validator: ^5.0.2
  pubspec_parse: ^1.5.0
  path: ^1.9.1
