name: gatekeeper
description: Gatekeeper is a Dart package for managing TCP ports with a manager, server, and client. Control ports programmatically, via IPC, or remotely for efficient port management.
version: 1.0.2
repository: https://github.com/gmpassos/gatekeeper

environment:
  sdk: ^3.6.0

executables:
  gatekeeper:
  gatekeeper_client:

# Add regular dependencies here.
dependencies:
  args_simple: ^1.1.0
  dependency_validator: ^3.2.3

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
